import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "./components/MainHeader";
import UserInfoStoreProvider, { User } from "../stores/UserInfoStore";
import { getUser } from "@/lib/auth/getUser";
import { Toaster } from "react-hot-toast";
import Footer from "./components/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let userSession = await getUser();

  return (
    <html className="max-w-screen" lang="en">
      <body className={inter.className}>
        <UserInfoStoreProvider initialState={{ user: userSession }}>
          <MainHeader />
          {children}
          <Toaster />
          <Footer />
        </UserInfoStoreProvider>
      </body>
    </html>
  );
}
