import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "./components/MainHeader";
import UserInfoStoreProvider, { User } from "./components/stores/UserInfoStore";
import { cookies } from "next/headers";
import { get } from "./utils/customFetch";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let userSession: User;
  try {
    userSession = await get("/auth/session", {
      isCookie: cookies().toString(),
    });
  } catch (err) {
    console.log(err);
  }
  return (
    <html className="max-w-screen" lang="en">
      <body className={inter.className}>
        <UserInfoStoreProvider initialState={{ user: userSession }}>
          <MainHeader />
          {children}
        </UserInfoStoreProvider>
      </body>
    </html>
  );
}
