import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import MainHeader from "../Components/MainHeader";
import UserInfoStoreProvider from "../stores/UserInfoStore";
import { getUser } from "@/lib/auth/getUser";
import { Toaster } from "react-hot-toast";
import Footer from "../Components/Organisms/Footer";
import { Suspense } from "react";
import HeaderSkeleton from "../Components/HeaderSkeleton";
import { sleep } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function UserData({ children }: { children: React.ReactNode }) {
  const userSession = await getUser();
  await sleep(100);
  return (
    <UserInfoStoreProvider initialState={{ user: userSession }}>
      <MainHeader />
      {children}
    </UserInfoStoreProvider>
  );
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  console.log("layout", Date.now());
  return (
    <html className="max-w-screen" lang="en">
      <body className={inter.className}>
        <Suspense fallback={<HeaderSkeleton />}>
          <UserData>{children}</UserData>
        </Suspense>
        <Toaster />
        <Footer />
      </body>
    </html>
  );
}
